# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import subprocess
from PyQt6 import QtCore, QtGui, QtWidgets,QtWidgets, uic
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QApplication, QDialog, QMainWindow, QPushButton, QColorDialog, QFileDialog, QLabel
from pathlib import Path

initial_colors = ["#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff","#ffffff",
"#ffffff","#ffffff","#ffffff","#ffffff"]

colors_working = []

colors_working = initial_colors

if os.path.exists('bloody_keycolor.conf'):
    with open('bloody_keycolor.conf', 'r') as file:
        config = []
        for line in file:
            line = line.strip()
            config.append(line)
    file.close()
else:
    config = ['',str(Path.home()),str(Path.home())]

working_dir = config[1]
active_profile_dir = config[2]

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1024, 450)
        self.escape_0 = QtWidgets.QPushButton(parent=Widget)
        self.escape_0.setGeometry(QtCore.QRect(15, 157, 45, 45))
        self.escape_0.setDefault(False)
        self.escape_0.setFlat(False)
        self.escape_0.setObjectName("escape_0")
        self.f1_1 = QtWidgets.QPushButton(parent=Widget)
        self.f1_1.setGeometry(QtCore.QRect(103, 157, 45, 45))
        self.f1_1.setDefault(False)
        self.f1_1.setFlat(False)
        self.f1_1.setObjectName("f1_1")
        self.f2_2 = QtWidgets.QPushButton(parent=Widget)
        self.f2_2.setGeometry(QtCore.QRect(148, 157, 45, 45))
        self.f2_2.setDefault(False)
        self.f2_2.setFlat(False)
        self.f2_2.setObjectName("f2_2")
        self.f3_3 = QtWidgets.QPushButton(parent=Widget)
        self.f3_3.setGeometry(QtCore.QRect(193, 157, 45, 45))
        self.f3_3.setDefault(False)
        self.f3_3.setFlat(False)
        self.f3_3.setObjectName("f3_3")
        self.f4_4 = QtWidgets.QPushButton(parent=Widget)
        self.f4_4.setGeometry(QtCore.QRect(238, 157, 45, 45))
        self.f4_4.setDefault(False)
        self.f4_4.setFlat(False)
        self.f4_4.setObjectName("f4_4")
        self.f5_5 = QtWidgets.QPushButton(parent=Widget)
        self.f5_5.setGeometry(QtCore.QRect(301, 157, 45, 45))
        self.f5_5.setDefault(False)
        self.f5_5.setFlat(False)
        self.f5_5.setObjectName("f5_5")
        self.f6_6 = QtWidgets.QPushButton(parent=Widget)
        self.f6_6.setGeometry(QtCore.QRect(346, 157, 45, 45))
        self.f6_6.setDefault(False)
        self.f6_6.setFlat(False)
        self.f6_6.setObjectName("f6_6")
        self.f7_7 = QtWidgets.QPushButton(parent=Widget)
        self.f7_7.setGeometry(QtCore.QRect(391, 157, 45, 45))
        self.f7_7.setDefault(False)
        self.f7_7.setFlat(False)
        self.f7_7.setObjectName("f7_7")
        self.f8_8 = QtWidgets.QPushButton(parent=Widget)
        self.f8_8.setGeometry(QtCore.QRect(436, 157, 45, 45))
        self.f8_8.setDefault(False)
        self.f8_8.setFlat(False)
        self.f8_8.setObjectName("f8_8")
        self.f9_9 = QtWidgets.QPushButton(parent=Widget)
        self.f9_9.setGeometry(QtCore.QRect(497, 157, 45, 45))
        self.f9_9.setDefault(False)
        self.f9_9.setFlat(False)
        self.f9_9.setObjectName("f9_9")
        self.f10_10 = QtWidgets.QPushButton(parent=Widget)
        self.f10_10.setGeometry(QtCore.QRect(542, 157, 45, 45))
        self.f10_10.setDefault(False)
        self.f10_10.setFlat(False)
        self.f10_10.setObjectName("f10_10")
        self.f11_11 = QtWidgets.QPushButton(parent=Widget)
        self.f11_11.setGeometry(QtCore.QRect(587, 157, 45, 45))
        self.f11_11.setDefault(False)
        self.f11_11.setFlat(False)
        self.f11_11.setObjectName("f11_11")
        self.f12_12 = QtWidgets.QPushButton(parent=Widget)
        self.f12_12.setGeometry(QtCore.QRect(632, 157, 45, 45))
        self.f12_12.setDefault(False)
        self.f12_12.setFlat(False)
        self.f12_12.setObjectName("f12_12")
        self.prtsc_13 = QtWidgets.QPushButton(parent=Widget)
        self.prtsc_13.setGeometry(QtCore.QRect(875, 157, 45, 45))
        self.prtsc_13.setDefault(False)
        self.prtsc_13.setFlat(False)
        self.prtsc_13.setObjectName("prtsc_13")
        self.scrolllock_14 = QtWidgets.QPushButton(parent=Widget)
        self.scrolllock_14.setGeometry(QtCore.QRect(920, 157, 45, 45))
        self.scrolllock_14.setDefault(False)
        self.scrolllock_14.setFlat(False)
        self.scrolllock_14.setObjectName("scrolllock_14")
        self.pause_15 = QtWidgets.QPushButton(parent=Widget)
        self.pause_15.setGeometry(QtCore.QRect(965, 157, 45, 45))
        self.pause_15.setDefault(False)
        self.pause_15.setFlat(False)
        self.pause_15.setObjectName("pause_15")
        self.backtick_16 = QtWidgets.QPushButton(parent=Widget)
        self.backtick_16.setGeometry(QtCore.QRect(15, 215, 45, 45))
        self.backtick_16.setDefault(False)
        self.backtick_16.setFlat(False)
        self.backtick_16.setObjectName("backtick_16")
        self.onekey_17 = QtWidgets.QPushButton(parent=Widget)
        self.onekey_17.setGeometry(QtCore.QRect(60, 215, 45, 45))
        self.onekey_17.setDefault(False)
        self.onekey_17.setFlat(False)
        self.onekey_17.setObjectName("onekey_17")
        self.twokey_18 = QtWidgets.QPushButton(parent=Widget)
        self.twokey_18.setGeometry(QtCore.QRect(105, 215, 45, 45))
        self.twokey_18.setDefault(False)
        self.twokey_18.setFlat(False)
        self.twokey_18.setObjectName("twokey_18")
        self.threekey_19 = QtWidgets.QPushButton(parent=Widget)
        self.threekey_19.setGeometry(QtCore.QRect(150, 215, 45, 45))
        self.threekey_19.setDefault(False)
        self.threekey_19.setFlat(False)
        self.threekey_19.setObjectName("threekey_19")
        self.fourkey_20 = QtWidgets.QPushButton(parent=Widget)
        self.fourkey_20.setGeometry(QtCore.QRect(195, 215, 45, 45))
        self.fourkey_20.setDefault(False)
        self.fourkey_20.setFlat(False)
        self.fourkey_20.setObjectName("fourkey_20")
        self.fivekey_21 = QtWidgets.QPushButton(parent=Widget)
        self.fivekey_21.setGeometry(QtCore.QRect(240, 215, 45, 45))
        self.fivekey_21.setDefault(False)
        self.fivekey_21.setFlat(False)
        self.fivekey_21.setObjectName("fivekey_21")
        self.sixkey_22 = QtWidgets.QPushButton(parent=Widget)
        self.sixkey_22.setGeometry(QtCore.QRect(285, 215, 45, 45))
        self.sixkey_22.setDefault(False)
        self.sixkey_22.setFlat(False)
        self.sixkey_22.setObjectName("sixkey_22")
        self.sevenkey_23 = QtWidgets.QPushButton(parent=Widget)
        self.sevenkey_23.setGeometry(QtCore.QRect(330, 215, 45, 45))
        self.sevenkey_23.setDefault(False)
        self.sevenkey_23.setFlat(False)
        self.sevenkey_23.setObjectName("sevenkey_23")
        self.eightkey_24 = QtWidgets.QPushButton(parent=Widget)
        self.eightkey_24.setGeometry(QtCore.QRect(374, 215, 45, 45))
        self.eightkey_24.setDefault(False)
        self.eightkey_24.setFlat(False)
        self.eightkey_24.setObjectName("eightkey_24")
        self.ninekey_25 = QtWidgets.QPushButton(parent=Widget)
        self.ninekey_25.setGeometry(QtCore.QRect(419, 215, 45, 45))
        self.ninekey_25.setDefault(False)
        self.ninekey_25.setFlat(False)
        self.ninekey_25.setObjectName("ninekey_25")
        self.zerokey_26 = QtWidgets.QPushButton(parent=Widget)
        self.zerokey_26.setGeometry(QtCore.QRect(464, 215, 45, 45))
        self.zerokey_26.setDefault(False)
        self.zerokey_26.setFlat(False)
        self.zerokey_26.setObjectName("zerokey_26")
        self.minuskey_27 = QtWidgets.QPushButton(parent=Widget)
        self.minuskey_27.setGeometry(QtCore.QRect(509, 215, 45, 45))
        self.minuskey_27.setDefault(False)
        self.minuskey_27.setFlat(False)
        self.minuskey_27.setObjectName("minuskey_27")
        self.equalskey_28 = QtWidgets.QPushButton(parent=Widget)
        self.equalskey_28.setGeometry(QtCore.QRect(554, 215, 45, 45))
        self.equalskey_28.setDefault(False)
        self.equalskey_28.setFlat(False)
        self.equalskey_28.setObjectName("equalskey_28")
        self.backspace_29 = QtWidgets.QPushButton(parent=Widget)
        self.backspace_29.setGeometry(QtCore.QRect(598, 215, 79, 45))
        self.backspace_29.setDefault(False)
        self.backspace_29.setFlat(False)
        self.backspace_29.setObjectName("backspace_29")
        self.nsert_30 = QtWidgets.QPushButton(parent=Widget)
        self.nsert_30.setGeometry(QtCore.QRect(686, 215, 45, 45))
        self.nsert_30.setDefault(False)
        self.nsert_30.setFlat(False)
        self.nsert_30.setObjectName("nsert_30")
        self.home_31 = QtWidgets.QPushButton(parent=Widget)
        self.home_31.setGeometry(QtCore.QRect(731, 215, 45, 45))
        self.home_31.setDefault(False)
        self.home_31.setFlat(False)
        self.home_31.setObjectName("home_31")
        self.pageup_32 = QtWidgets.QPushButton(parent=Widget)
        self.pageup_32.setGeometry(QtCore.QRect(776, 215, 45, 45))
        self.pageup_32.setDefault(False)
        self.pageup_32.setFlat(False)
        self.pageup_32.setObjectName("pageup_32")
        self.numlock_33 = QtWidgets.QPushButton(parent=Widget)
        self.numlock_33.setGeometry(QtCore.QRect(830, 215, 45, 45))
        self.numlock_33.setDefault(False)
        self.numlock_33.setFlat(False)
        self.numlock_33.setObjectName("numlock_33")
        self.vide_34 = QtWidgets.QPushButton(parent=Widget)
        self.vide_34.setGeometry(QtCore.QRect(875, 215, 45, 45))
        self.vide_34.setDefault(False)
        self.vide_34.setFlat(False)
        self.vide_34.setObjectName("vide_34")
        self.multiply_35 = QtWidgets.QPushButton(parent=Widget)
        self.multiply_35.setGeometry(QtCore.QRect(920, 215, 45, 45))
        self.multiply_35.setDefault(False)
        self.multiply_35.setFlat(False)
        self.multiply_35.setObjectName("multiply_35")
        self.subtract_36 = QtWidgets.QPushButton(parent=Widget)
        self.subtract_36.setGeometry(QtCore.QRect(965, 215, 45, 45))
        self.subtract_36.setDefault(False)
        self.subtract_36.setFlat(False)
        self.subtract_36.setObjectName("subtract_36")
        self.tab_37 = QtWidgets.QPushButton(parent=Widget)
        self.tab_37.setGeometry(QtCore.QRect(15, 260, 67, 45))
        self.tab_37.setDefault(False)
        self.tab_37.setFlat(False)
        self.tab_37.setObjectName("tab_37")
        self.q_38 = QtWidgets.QPushButton(parent=Widget)
        self.q_38.setGeometry(QtCore.QRect(82, 260, 45, 45))
        self.q_38.setDefault(False)
        self.q_38.setFlat(False)
        self.q_38.setObjectName("q_38")
        self.w_39 = QtWidgets.QPushButton(parent=Widget)
        self.w_39.setGeometry(QtCore.QRect(127, 260, 45, 45))
        self.w_39.setDefault(False)
        self.w_39.setFlat(False)
        self.w_39.setObjectName("w_39")
        self.e_40 = QtWidgets.QPushButton(parent=Widget)
        self.e_40.setGeometry(QtCore.QRect(172, 260, 45, 45))
        self.e_40.setDefault(False)
        self.e_40.setFlat(False)
        self.e_40.setObjectName("e_40")
        self.r_41 = QtWidgets.QPushButton(parent=Widget)
        self.r_41.setGeometry(QtCore.QRect(217, 260, 45, 45))
        self.r_41.setDefault(False)
        self.r_41.setFlat(False)
        self.r_41.setObjectName("r_41")
        self.t_42 = QtWidgets.QPushButton(parent=Widget)
        self.t_42.setGeometry(QtCore.QRect(262, 260, 45, 45))
        self.t_42.setDefault(False)
        self.t_42.setFlat(False)
        self.t_42.setObjectName("t_42")
        self.y_43 = QtWidgets.QPushButton(parent=Widget)
        self.y_43.setGeometry(QtCore.QRect(307, 260, 45, 45))
        self.y_43.setDefault(False)
        self.y_43.setFlat(False)
        self.y_43.setObjectName("y_43")
        self.u_44 = QtWidgets.QPushButton(parent=Widget)
        self.u_44.setGeometry(QtCore.QRect(352, 260, 45, 45))
        self.u_44.setDefault(False)
        self.u_44.setFlat(False)
        self.u_44.setObjectName("u_44")
        self._45 = QtWidgets.QPushButton(parent=Widget)
        self._45.setGeometry(QtCore.QRect(396, 260, 45, 45))
        self._45.setDefault(False)
        self._45.setFlat(False)
        self._45.setObjectName("_45")
        self.o_46 = QtWidgets.QPushButton(parent=Widget)
        self.o_46.setGeometry(QtCore.QRect(441, 260, 45, 45))
        self.o_46.setDefault(False)
        self.o_46.setFlat(False)
        self.o_46.setObjectName("o_46")
        self.p_47 = QtWidgets.QPushButton(parent=Widget)
        self.p_47.setGeometry(QtCore.QRect(486, 260, 45, 45))
        self.p_47.setDefault(False)
        self.p_47.setFlat(False)
        self.p_47.setObjectName("p_47")
        self.lbracket_48 = QtWidgets.QPushButton(parent=Widget)
        self.lbracket_48.setGeometry(QtCore.QRect(531, 260, 45, 45))
        self.lbracket_48.setDefault(False)
        self.lbracket_48.setFlat(False)
        self.lbracket_48.setObjectName("lbracket_48")
        self.rbracket_49 = QtWidgets.QPushButton(parent=Widget)
        self.rbracket_49.setGeometry(QtCore.QRect(576, 260, 45, 45))
        self.rbracket_49.setDefault(False)
        self.rbracket_49.setFlat(False)
        self.rbracket_49.setObjectName("rbracket_49")
        self.backslash_50 = QtWidgets.QPushButton(parent=Widget)
        self.backslash_50.setGeometry(QtCore.QRect(621, 260, 56, 45))
        self.backslash_50.setDefault(False)
        self.backslash_50.setFlat(False)
        self.backslash_50.setObjectName("backslash_50")
        self.elete_51 = QtWidgets.QPushButton(parent=Widget)
        self.elete_51.setGeometry(QtCore.QRect(686, 260, 45, 45))
        self.elete_51.setDefault(False)
        self.elete_51.setFlat(False)
        self.elete_51.setObjectName("elete_51")
        self.end_52 = QtWidgets.QPushButton(parent=Widget)
        self.end_52.setGeometry(QtCore.QRect(731, 260, 45, 45))
        self.end_52.setDefault(False)
        self.end_52.setFlat(False)
        self.end_52.setObjectName("end_52")
        self.pagedown_53 = QtWidgets.QPushButton(parent=Widget)
        self.pagedown_53.setGeometry(QtCore.QRect(776, 260, 45, 45))
        self.pagedown_53.setDefault(False)
        self.pagedown_53.setFlat(False)
        self.pagedown_53.setObjectName("pagedown_53")
        self.numseven_54 = QtWidgets.QPushButton(parent=Widget)
        self.numseven_54.setGeometry(QtCore.QRect(830, 260, 45, 45))
        self.numseven_54.setDefault(False)
        self.numseven_54.setFlat(False)
        self.numseven_54.setObjectName("numseven_54")
        self.numeight_55 = QtWidgets.QPushButton(parent=Widget)
        self.numeight_55.setGeometry(QtCore.QRect(875, 260, 45, 45))
        self.numeight_55.setDefault(False)
        self.numeight_55.setFlat(False)
        self.numeight_55.setObjectName("numeight_55")
        self.numnine_56 = QtWidgets.QPushButton(parent=Widget)
        self.numnine_56.setGeometry(QtCore.QRect(920, 260, 45, 45))
        self.numnine_56.setDefault(False)
        self.numnine_56.setFlat(False)
        self.numnine_56.setObjectName("numnine_56")
        self.add_57 = QtWidgets.QPushButton(parent=Widget)
        self.add_57.setGeometry(QtCore.QRect(965, 260, 45, 90))
        self.add_57.setDefault(False)
        self.add_57.setFlat(False)
        self.add_57.setObjectName("add_57")
        self.capslock_58 = QtWidgets.QPushButton(parent=Widget)
        self.capslock_58.setGeometry(QtCore.QRect(15, 304, 78, 45))
        self.capslock_58.setDefault(False)
        self.capslock_58.setFlat(False)
        self.capslock_58.setObjectName("capslock_58")
        self.a_59 = QtWidgets.QPushButton(parent=Widget)
        self.a_59.setGeometry(QtCore.QRect(92, 304, 45, 45))
        self.a_59.setDefault(False)
        self.a_59.setFlat(False)
        self.a_59.setObjectName("a_59")
        self.s_60 = QtWidgets.QPushButton(parent=Widget)
        self.s_60.setGeometry(QtCore.QRect(137, 304, 45, 45))
        self.s_60.setDefault(False)
        self.s_60.setFlat(False)
        self.s_60.setObjectName("s_60")
        self._61 = QtWidgets.QPushButton(parent=Widget)
        self._61.setGeometry(QtCore.QRect(182, 304, 45, 45))
        self._61.setDefault(False)
        self._61.setFlat(False)
        self._61.setObjectName("_61")
        self.f_62 = QtWidgets.QPushButton(parent=Widget)
        self.f_62.setGeometry(QtCore.QRect(227, 304, 45, 45))
        self.f_62.setDefault(False)
        self.f_62.setFlat(False)
        self.f_62.setObjectName("f_62")
        self.g_63 = QtWidgets.QPushButton(parent=Widget)
        self.g_63.setGeometry(QtCore.QRect(272, 304, 45, 45))
        self.g_63.setDefault(False)
        self.g_63.setFlat(False)
        self.g_63.setObjectName("g_63")
        self.h_64 = QtWidgets.QPushButton(parent=Widget)
        self.h_64.setGeometry(QtCore.QRect(317, 304, 45, 45))
        self.h_64.setDefault(False)
        self.h_64.setFlat(False)
        self.h_64.setObjectName("h_64")
        self.j_65 = QtWidgets.QPushButton(parent=Widget)
        self.j_65.setGeometry(QtCore.QRect(362, 304, 45, 45))
        self.j_65.setDefault(False)
        self.j_65.setFlat(False)
        self.j_65.setObjectName("j_65")
        self.k_66 = QtWidgets.QPushButton(parent=Widget)
        self.k_66.setGeometry(QtCore.QRect(406, 304, 45, 45))
        self.k_66.setDefault(False)
        self.k_66.setFlat(False)
        self.k_66.setObjectName("k_66")
        self.l_67 = QtWidgets.QPushButton(parent=Widget)
        self.l_67.setGeometry(QtCore.QRect(451, 304, 45, 45))
        self.l_67.setDefault(False)
        self.l_67.setFlat(False)
        self.l_67.setObjectName("l_67")
        self.semicolon_68 = QtWidgets.QPushButton(parent=Widget)
        self.semicolon_68.setGeometry(QtCore.QRect(496, 304, 45, 45))
        self.semicolon_68.setDefault(False)
        self.semicolon_68.setFlat(False)
        self.semicolon_68.setObjectName("semicolon_68")
        self.quote_69 = QtWidgets.QPushButton(parent=Widget)
        self.quote_69.setGeometry(QtCore.QRect(541, 304, 45, 45))
        self.quote_69.setDefault(False)
        self.quote_69.setFlat(False)
        self.quote_69.setObjectName("quote_69")
        self.enter_70 = QtWidgets.QPushButton(parent=Widget)
        self.enter_70.setGeometry(QtCore.QRect(586, 304, 91, 45))
        self.enter_70.setDefault(False)
        self.enter_70.setFlat(False)
        self.enter_70.setObjectName("enter_70")
        self.numfour_71 = QtWidgets.QPushButton(parent=Widget)
        self.numfour_71.setGeometry(QtCore.QRect(830, 304, 45, 45))
        self.numfour_71.setDefault(False)
        self.numfour_71.setFlat(False)
        self.numfour_71.setObjectName("numfour_71")
        self.numfive_72 = QtWidgets.QPushButton(parent=Widget)
        self.numfive_72.setGeometry(QtCore.QRect(875, 304, 45, 45))
        self.numfive_72.setDefault(False)
        self.numfive_72.setFlat(False)
        self.numfive_72.setObjectName("numfive_72")
        self.numsix_73 = QtWidgets.QPushButton(parent=Widget)
        self.numsix_73.setGeometry(QtCore.QRect(920, 304, 45, 45))
        self.numsix_73.setDefault(False)
        self.numsix_73.setFlat(False)
        self.numsix_73.setObjectName("numsix_73")
        self.lshift_74 = QtWidgets.QPushButton(parent=Widget)
        self.lshift_74.setGeometry(QtCore.QRect(15, 349, 100, 45))
        self.lshift_74.setDefault(False)
        self.lshift_74.setFlat(False)
        self.lshift_74.setObjectName("lshift_74")
        self.z_75 = QtWidgets.QPushButton(parent=Widget)
        self.z_75.setGeometry(QtCore.QRect(115, 349, 45, 45))
        self.z_75.setDefault(False)
        self.z_75.setFlat(False)
        self.z_75.setObjectName("z_75")
        self.x_76 = QtWidgets.QPushButton(parent=Widget)
        self.x_76.setGeometry(QtCore.QRect(160, 349, 45, 45))
        self.x_76.setDefault(False)
        self.x_76.setFlat(False)
        self.x_76.setObjectName("x_76")
        self.c_77 = QtWidgets.QPushButton(parent=Widget)
        self.c_77.setGeometry(QtCore.QRect(205, 349, 45, 45))
        self.c_77.setDefault(False)
        self.c_77.setFlat(False)
        self.c_77.setObjectName("c_77")
        self.v_78 = QtWidgets.QPushButton(parent=Widget)
        self.v_78.setGeometry(QtCore.QRect(250, 349, 45, 45))
        self.v_78.setDefault(False)
        self.v_78.setFlat(False)
        self.v_78.setObjectName("v_78")
        self.b_79 = QtWidgets.QPushButton(parent=Widget)
        self.b_79.setGeometry(QtCore.QRect(295, 349, 45, 45))
        self.b_79.setDefault(False)
        self.b_79.setFlat(False)
        self.b_79.setObjectName("b_79")
        self.n_80 = QtWidgets.QPushButton(parent=Widget)
        self.n_80.setGeometry(QtCore.QRect(340, 349, 45, 45))
        self.n_80.setDefault(False)
        self.n_80.setFlat(False)
        self.n_80.setObjectName("n_80")
        self.m_81 = QtWidgets.QPushButton(parent=Widget)
        self.m_81.setGeometry(QtCore.QRect(385, 349, 45, 45))
        self.m_81.setDefault(False)
        self.m_81.setFlat(False)
        self.m_81.setObjectName("m_81")
        self.comma_82 = QtWidgets.QPushButton(parent=Widget)
        self.comma_82.setGeometry(QtCore.QRect(429, 349, 45, 45))
        self.comma_82.setDefault(False)
        self.comma_82.setFlat(False)
        self.comma_82.setObjectName("comma_82")
        self.period_83 = QtWidgets.QPushButton(parent=Widget)
        self.period_83.setGeometry(QtCore.QRect(474, 349, 45, 45))
        self.period_83.setDefault(False)
        self.period_83.setFlat(False)
        self.period_83.setObjectName("period_83")
        self.forewardslash_84 = QtWidgets.QPushButton(parent=Widget)
        self.forewardslash_84.setGeometry(QtCore.QRect(519, 349, 45, 45))
        self.forewardslash_84.setDefault(False)
        self.forewardslash_84.setFlat(False)
        self.forewardslash_84.setObjectName("forewardslash_84")
        self.rshift_85 = QtWidgets.QPushButton(parent=Widget)
        self.rshift_85.setGeometry(QtCore.QRect(564, 349, 113, 45))
        self.rshift_85.setDefault(False)
        self.rshift_85.setFlat(False)
        self.rshift_85.setObjectName("rshift_85")
        self.up_86 = QtWidgets.QPushButton(parent=Widget)
        self.up_86.setGeometry(QtCore.QRect(731, 349, 45, 45))
        self.up_86.setDefault(False)
        self.up_86.setFlat(False)
        self.up_86.setObjectName("up_86")
        self.numone_87 = QtWidgets.QPushButton(parent=Widget)
        self.numone_87.setGeometry(QtCore.QRect(830, 349, 45, 45))
        self.numone_87.setDefault(False)
        self.numone_87.setFlat(False)
        self.numone_87.setObjectName("numone_87")
        self.numtwo_88 = QtWidgets.QPushButton(parent=Widget)
        self.numtwo_88.setGeometry(QtCore.QRect(875, 349, 45, 45))
        self.numtwo_88.setDefault(False)
        self.numtwo_88.setFlat(False)
        self.numtwo_88.setObjectName("numtwo_88")
        self.numthree_89 = QtWidgets.QPushButton(parent=Widget)
        self.numthree_89.setGeometry(QtCore.QRect(920, 349, 45, 45))
        self.numthree_89.setDefault(False)
        self.numthree_89.setFlat(False)
        self.numthree_89.setObjectName("numthree_89")
        self.numenter_90 = QtWidgets.QPushButton(parent=Widget)
        self.numenter_90.setGeometry(QtCore.QRect(965, 349, 45, 90))
        self.numenter_90.setDefault(False)
        self.numenter_90.setFlat(False)
        self.numenter_90.setObjectName("numenter_90")
        self.control_91 = QtWidgets.QPushButton(parent=Widget)
        self.control_91.setGeometry(QtCore.QRect(15, 394, 55, 45))
        self.control_91.setDefault(False)
        self.control_91.setFlat(False)
        self.control_91.setObjectName("control_91")
        self.super_92 = QtWidgets.QPushButton(parent=Widget)
        self.super_92.setGeometry(QtCore.QRect(70, 394, 57, 45))
        self.super_92.setDefault(False)
        self.super_92.setFlat(False)
        self.super_92.setObjectName("super_92")
        self.alt_93 = QtWidgets.QPushButton(parent=Widget)
        self.alt_93.setGeometry(QtCore.QRect(127, 394, 55, 45))
        self.alt_93.setDefault(False)
        self.alt_93.setFlat(False)
        self.alt_93.setObjectName("alt_93")
        self.space_94 = QtWidgets.QPushButton(parent=Widget)
        self.space_94.setGeometry(QtCore.QRect(182, 394, 275, 45))
        self.space_94.setDefault(False)
        self.space_94.setFlat(False)
        self.space_94.setObjectName("space_94")
        self.ralt_95 = QtWidgets.QPushButton(parent=Widget)
        self.ralt_95.setGeometry(QtCore.QRect(457, 394, 56, 45))
        self.ralt_95.setDefault(False)
        self.ralt_95.setFlat(False)
        self.ralt_95.setObjectName("ralt_95")
        self.fn_96 = QtWidgets.QPushButton(parent=Widget)
        self.fn_96.setGeometry(QtCore.QRect(513, 394, 54, 45))
        self.fn_96.setDefault(False)
        self.fn_96.setFlat(False)
        self.fn_96.setObjectName("fn_96")
        self.menu_97 = QtWidgets.QPushButton(parent=Widget)
        self.menu_97.setGeometry(QtCore.QRect(567, 394, 55, 45))
        self.menu_97.setDefault(False)
        self.menu_97.setFlat(False)
        self.menu_97.setObjectName("menu_97")
        self.rcontrol_98 = QtWidgets.QPushButton(parent=Widget)
        self.rcontrol_98.setGeometry(QtCore.QRect(622, 394, 55, 45))
        self.rcontrol_98.setDefault(False)
        self.rcontrol_98.setFlat(False)
        self.rcontrol_98.setObjectName("rcontrol_98")
        self.left_99 = QtWidgets.QPushButton(parent=Widget)
        self.left_99.setGeometry(QtCore.QRect(686, 394, 45, 45))
        self.left_99.setDefault(False)
        self.left_99.setFlat(False)
        self.left_99.setObjectName("left_99")
        self.own_100 = QtWidgets.QPushButton(parent=Widget)
        self.own_100.setGeometry(QtCore.QRect(731, 394, 45, 45))
        self.own_100.setDefault(False)
        self.own_100.setFlat(False)
        self.own_100.setObjectName("own_100")
        self.right_101 = QtWidgets.QPushButton(parent=Widget)
        self.right_101.setGeometry(QtCore.QRect(776, 394, 45, 45))
        self.right_101.setDefault(False)
        self.right_101.setFlat(False)
        self.right_101.setObjectName("right_101")
        self.numzero_102 = QtWidgets.QPushButton(parent=Widget)
        self.numzero_102.setGeometry(QtCore.QRect(830, 394, 90, 45))
        self.numzero_102.setDefault(False)
        self.numzero_102.setFlat(False)
        self.numzero_102.setObjectName("numzero_102")
        self.ecimalpoint_103 = QtWidgets.QPushButton(parent=Widget)
        self.ecimalpoint_103.setGeometry(QtCore.QRect(920, 394, 45, 45))
        self.ecimalpoint_103.setDefault(False)
        self.ecimalpoint_103.setFlat(False)
        self.ecimalpoint_103.setObjectName("ecimalpoint_103")
        self.load = QtWidgets.QPushButton(parent=Widget)
        self.load.setGeometry(QtCore.QRect(15, 13, 78, 31))
        self.load.setDefault(False)
        self.load.setFlat(False)
        self.load.setObjectName("load")
        self.save = QtWidgets.QPushButton(parent=Widget)
        self.save.setGeometry(QtCore.QRect(104, 13, 78, 31))
        self.save.setDefault(False)
        self.save.setFlat(False)
        self.save.setObjectName("save")
        self.parse = QtWidgets.QPushButton(parent=Widget)
        self.parse.setGeometry(QtCore.QRect(194, 13, 78, 31))
        self.parse.setDefault(False)
        self.parse.setFlat(False)
        self.parse.setObjectName("parse")
        self.setall = QtWidgets.QPushButton(parent=Widget)
        self.setall.setGeometry(QtCore.QRect(920, 13, 90, 31))
        self.setall.setDefault(False)
        self.setall.setFlat(False)
        self.setall.setObjectName("setall")
        self.runscript = QtWidgets.QPushButton(parent=Widget)
        self.runscript.setGeometry(QtCore.QRect(284, 13, 78, 31))
        self.runscript.setDefault(False)
        self.runscript.setFlat(False)
        self.runscript.setObjectName("runscript")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Bloody Color Picker"))
        self.escape_0.setText(_translate("Widget", "ESC"))
        self.f1_1.setText(_translate("Widget", "F1"))
        self.f2_2.setText(_translate("Widget", "F2"))
        self.f3_3.setText(_translate("Widget", "F3"))
        self.f4_4.setText(_translate("Widget", "F4"))
        self.f5_5.setText(_translate("Widget", "F5"))
        self.f6_6.setText(_translate("Widget", "F6"))
        self.f7_7.setText(_translate("Widget", "F7"))
        self.f8_8.setText(_translate("Widget", "F8"))
        self.f9_9.setText(_translate("Widget", "F9"))
        self.f10_10.setText(_translate("Widget", "F10"))
        self.f11_11.setText(_translate("Widget", "F11"))
        self.f12_12.setText(_translate("Widget", "F12"))
        self.prtsc_13.setText(_translate("Widget", "PrtSc"))
        self.scrolllock_14.setText(_translate("Widget", "ScrL"))
        self.pause_15.setText(_translate("Widget", "Pause"))
        self.backtick_16.setText(_translate("Widget", "~ `"))
        self.onekey_17.setText(_translate("Widget", "1 !"))
        self.twokey_18.setText(_translate("Widget", "2 @"))
        self.threekey_19.setText(_translate("Widget", "3 #"))
        self.fourkey_20.setText(_translate("Widget", "4 $"))
        self.fivekey_21.setText(_translate("Widget", "5 %"))
        self.sixkey_22.setText(_translate("Widget", "6 ^"))
        self.sevenkey_23.setText(_translate("Widget", "7"))
        self.eightkey_24.setText(_translate("Widget", "8 *"))
        self.ninekey_25.setText(_translate("Widget", "9 ("))
        self.zerokey_26.setText(_translate("Widget", "0 "))
        self.minuskey_27.setText(_translate("Widget", "- _"))
        self.equalskey_28.setText(_translate("Widget", "= +"))
        self.backspace_29.setText(_translate("Widget", "Backspace"))
        self.nsert_30.setText(_translate("Widget", "Insert"))
        self.home_31.setText(_translate("Widget", "Home"))
        self.pageup_32.setText(_translate("Widget", "PageUp"))
        self.numlock_33.setText(_translate("Widget", "NLock"))
        self.vide_34.setText(_translate("Widget", "/"))
        self.multiply_35.setText(_translate("Widget", "*"))
        self.subtract_36.setText(_translate("Widget", "-"))
        self.tab_37.setText(_translate("Widget", "Tab"))
        self.q_38.setText(_translate("Widget", "Q"))
        self.w_39.setText(_translate("Widget", "W"))
        self.e_40.setText(_translate("Widget", "E"))
        self.r_41.setText(_translate("Widget", "R"))
        self.t_42.setText(_translate("Widget", "T"))
        self.y_43.setText(_translate("Widget", "Y"))
        self.u_44.setText(_translate("Widget", "U"))
        self._45.setText(_translate("Widget", "I"))
        self.o_46.setText(_translate("Widget", "O"))
        self.p_47.setText(_translate("Widget", "P"))
        self.lbracket_48.setText(_translate("Widget", "[ {"))
        self.rbracket_49.setText(_translate("Widget", "] }"))
        self.backslash_50.setText(_translate("Widget", "\\ |"))
        self.elete_51.setText(_translate("Widget", "Del"))
        self.end_52.setText(_translate("Widget", "End"))
        self.pagedown_53.setText(_translate("Widget", "PageDn"))
        self.numseven_54.setText(_translate("Widget", "7"))
        self.numeight_55.setText(_translate("Widget", "8"))
        self.numnine_56.setText(_translate("Widget", "9"))
        self.add_57.setText(_translate("Widget", "+"))
        self.capslock_58.setText(_translate("Widget", "Caps Lock"))
        self.a_59.setText(_translate("Widget", "A"))
        self.s_60.setText(_translate("Widget", "S"))
        self._61.setText(_translate("Widget", "D"))
        self.f_62.setText(_translate("Widget", "F"))
        self.g_63.setText(_translate("Widget", "G"))
        self.h_64.setText(_translate("Widget", "H"))
        self.j_65.setText(_translate("Widget", "J"))
        self.k_66.setText(_translate("Widget", "K"))
        self.l_67.setText(_translate("Widget", "L"))
        self.semicolon_68.setText(_translate("Widget", "; :"))
        self.quote_69.setText(_translate("Widget", "\' \\"))
        self.enter_70.setText(_translate("Widget", "Enter"))
        self.numfour_71.setText(_translate("Widget", "4"))
        self.numfive_72.setText(_translate("Widget", "5"))
        self.numsix_73.setText(_translate("Widget", "6"))
        self.lshift_74.setText(_translate("Widget", "Shift"))
        self.z_75.setText(_translate("Widget", "Z"))
        self.x_76.setText(_translate("Widget", "X"))
        self.c_77.setText(_translate("Widget", "C"))
        self.v_78.setText(_translate("Widget", "V"))
        self.b_79.setText(_translate("Widget", "B"))
        self.n_80.setText(_translate("Widget", "N"))
        self.m_81.setText(_translate("Widget", "M"))
        self.comma_82.setText(_translate("Widget", ", <"))
        self.period_83.setText(_translate("Widget", ". >"))
        self.forewardslash_84.setText(_translate("Widget", "/ ?"))
        self.rshift_85.setText(_translate("Widget", "Shift"))
        self.up_86.setText(_translate("Widget", "Up"))
        self.numone_87.setText(_translate("Widget", "1"))
        self.numtwo_88.setText(_translate("Widget", "2"))
        self.numthree_89.setText(_translate("Widget", "3"))
        self.numenter_90.setText(_translate("Widget", "Enter"))
        self.control_91.setText(_translate("Widget", "Ctrl"))
        self.super_92.setText(_translate("Widget", "Super"))
        self.alt_93.setText(_translate("Widget", "Alt"))
        self.space_94.setText(_translate("Widget", "Space"))
        self.ralt_95.setText(_translate("Widget", "Alt"))
        self.fn_96.setText(_translate("Widget", "Fn"))
        self.menu_97.setText(_translate("Widget", "Menu"))
        self.rcontrol_98.setText(_translate("Widget", "Ctrl"))
        self.left_99.setText(_translate("Widget", "Left"))
        self.own_100.setText(_translate("Widget", "Down"))
        self.right_101.setText(_translate("Widget", "Right"))
        self.numzero_102.setText(_translate("Widget", "0"))
        self.ecimalpoint_103.setText(_translate("Widget", "."))
        self.load.setText(_translate("Widget", "load"))
        self.save.setText(_translate("Widget", "Save"))
        self.parse.setText(_translate("Widget", "Parse"))
        self.setall.setText(_translate("Widget", "Set All"))
        self.runscript.setText(_translate("Widget","Run Script"))
        self.runscript.setStyleSheet('QPushButton {background-color: gray; color: black;}')
        self.setall.setStyleSheet('QPushButton {background-color: gray; color: black;}')
        self.parse.setStyleSheet('QPushButton {background-color: gray; color: black;}')
        self.save.setStyleSheet('QPushButton {background-color: gray; color: black;}')
        self.load.setStyleSheet('QPushButton {background-color: gray; color: black;}')

class MainWindow(QtWidgets.QMainWindow, Ui_Widget):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)
        self.load_logo()
        self.make_key_connections()
        self.update_working_colors()
        self.active_directory = working_dir+"/"
        self.profile_directory = active_profile_dir+"/active_profile"
        self.script_directory = active_profile_dir+"/"
        
    def change_ad(self,directory):
        self.active_directory = directory
        
    def change_pd(self,directory):
        self.profile_directory = directory
    
    def save_clicked(self):
        self.save_file()
    
    def load_clicked(self):
        self.open_file()
        
    def runscript_clicked(self):
        try:
            subprocess.run(["python3",self.script_directory+"Set_Bloody_Key_Color.py"])
        except:
            self.runscript.setStyleSheet('QPushButton {background-color: red; color: black;}')
        
    def parse_clicked(self):
        fname = QFileDialog.getSaveFileName(self,"Parse file",self.profile_directory,'')
        if fname[0] != '':
            file = open(fname[0],'w')
            file.write('')
            file.close()
            file = open(fname[0], 'a')
            line = ""
            for index in range(0,58):
                line = line + str(colors_working[index])[1]+ str(colors_working[index])[2]
            file.write(line+"\n") 
            line = ""
            for index in range(58,104):
                line = line + str(colors_working[index])[1]+ str(colors_working[index])[2]
            file.write(line+"\n")
            line = ""
            for index in range(0,58):
                line = line + str(colors_working[index])[3]+ str(colors_working[index])[4]
            file.write(line+"\n") 
            line = ""
            for index in range(58,104):
                line = line + str(colors_working[index])[3]+ str(colors_working[index])[4]
            file.write(line+"\n")
            line = ""
            for index in range(0,58):
                line = line + str(colors_working[index])[5]+ str(colors_working[index])[6]
            file.write(line+"\n") 
            line = ""
            for index in range(58,104):
                line = line + str(colors_working[index])[5]+ str(colors_working[index])[6]
            file.write(line)
            file.close()
            self.change_pd(fname[0])
    
    def open_file(self):
        fname = QFileDialog.getOpenFileName(self, 'Open file', self.active_directory)
        if fname[0] != '':
            self.change_ad(fname[0])
            file = open(fname[0],'r')
            lines = []
            for line in file:
                line = line.strip()
                lines.append(line)
            file.close()
            for index in range(0,len(lines)):
                colors_working[index] = lines[index]
                self.update_working_colors()

    def save_file(self):
        fname = QFileDialog.getSaveFileName(self, 'Save file', self.active_directory)
        if fname[0] != '':
            file = open(fname[0],'w')
            file.write('')
            file.close()
            file = open(fname[0], 'a')
            for index in range(0,len(colors_working)):
                file.write(colors_working[index])
                if index != (len(colors_working)-1):
                    file.write("\n")
            file.close()
        
    def setall_clicked(self):
        color_dialog = QColorDialog.getColor()
        color_value = color_dialog.name()
        self.key_set_all(color_value)
     
    def key_set_color(self,index):
        color_dialog = QColorDialog.getColor()
        color_value = color_dialog.name()
        if color_value != colors_working[index]:
            colors_working[index] = color_value
            self.update_working_colors()
            return True
        else:
            return False
 
    def key_set_all(self,color):
        for index in range(0,len(colors_working)):
            colors_working[index] = str(color)
        self.update_working_colors()    
        
    def load_logo(self):
        if os.path.exists('bloody_logo.png'):
            label = QLabel(self)
            pixmap = QPixmap('bloody_logo.png')
            label.setPixmap(pixmap)
            label.setScaledContents(True)
            label.setGeometry(470,13,325,130)
    
    def make_key_connections(self):
        self.escape_0.clicked.connect(self.escape_0_clicked)
        self.f1_1.clicked.connect(self.f1_1_clicked)
        self.f2_2.clicked.connect(self.f2_2_clicked)
        self.f3_3.clicked.connect(self.f3_3_clicked)
        self.f4_4.clicked.connect(self.f4_4_clicked)
        self.f5_5.clicked.connect(self.f5_5_clicked)
        self.f6_6.clicked.connect(self.f6_6_clicked)
        self.f7_7.clicked.connect(self.f7_7_clicked)
        self.f8_8.clicked.connect(self.f8_8_clicked)
        self.f9_9.clicked.connect(self.f9_9_clicked)
        self.f10_10.clicked.connect(self.f10_10_clicked)
        self.f11_11.clicked.connect(self.f11_11_clicked)
        self.f12_12.clicked.connect(self.f12_12_clicked)
        self.prtsc_13.clicked.connect(self.prtsc_13_clicked)
        self.scrolllock_14.clicked.connect(self.scrolllock_14_clicked)
        self.pause_15.clicked.connect(self.pause_15_clicked)
        self.backtick_16.clicked.connect(self.backtick_16_clicked)
        self.onekey_17.clicked.connect(self.onekey_17_clicked)
        self.twokey_18.clicked.connect(self.twokey_18_clicked)
        self.threekey_19.clicked.connect(self.threekey_19_clicked)
        self.fourkey_20.clicked.connect(self.fourkey_20_clicked)
        self.fivekey_21.clicked.connect(self.fivekey_21_clicked)
        self.sixkey_22.clicked.connect(self.sixkey_22_clicked)
        self.sevenkey_23.clicked.connect(self.sevenkey_23_clicked)
        self.eightkey_24.clicked.connect(self.eightkey_24_clicked)
        self.ninekey_25.clicked.connect(self.ninekey_25_clicked)
        self.zerokey_26.clicked.connect(self.zerokey_26_clicked)
        self.minuskey_27.clicked.connect(self.minuskey_27_clicked)
        self.equalskey_28.clicked.connect(self.equalskey_28_clicked)
        self.backspace_29.clicked.connect(self.backspace_29_clicked)
        self.nsert_30.clicked.connect(self.nsert_30_clicked)
        self.home_31.clicked.connect(self.home_31_clicked)
        self.pageup_32.clicked.connect(self.pageup_32_clicked)
        self.numlock_33.clicked.connect(self.numlock_33_clicked)
        self.vide_34.clicked.connect(self.vide_34_clicked)
        self.multiply_35.clicked.connect(self.multiply_35_clicked)
        self.subtract_36.clicked.connect(self.subtract_36_clicked)
        self.tab_37.clicked.connect(self.tab_37_clicked)
        self.q_38.clicked.connect(self.q_38_clicked)
        self.w_39.clicked.connect(self.w_39_clicked)
        self.e_40.clicked.connect(self.e_40_clicked)
        self.r_41.clicked.connect(self.r_41_clicked)
        self.t_42.clicked.connect(self.t_42_clicked)
        self.y_43.clicked.connect(self.y_43_clicked)
        self.u_44.clicked.connect(self.u_44_clicked)
        self._45.clicked.connect(self._45_clicked)
        self.o_46.clicked.connect(self.o_46_clicked)
        self.p_47.clicked.connect(self.p_47_clicked)
        self.lbracket_48.clicked.connect(self.lbracket_48_clicked)
        self.rbracket_49.clicked.connect(self.rbracket_49_clicked)
        self.backslash_50.clicked.connect(self.backslash_50_clicked)
        self.elete_51.clicked.connect(self.elete_51_clicked)
        self.end_52.clicked.connect(self.end_52_clicked)
        self.pagedown_53.clicked.connect(self.pagedown_53_clicked)
        self.numseven_54.clicked.connect(self.numseven_54_clicked)
        self.numeight_55.clicked.connect(self.numeight_55_clicked)
        self.numnine_56.clicked.connect(self.numnine_56_clicked)
        self.add_57.clicked.connect(self.add_57_clicked)
        self.capslock_58.clicked.connect(self.capslock_58_clicked)
        self.a_59.clicked.connect(self.a_59_clicked)
        self.s_60.clicked.connect(self.s_60_clicked)
        self._61.clicked.connect(self._61_clicked)
        self.f_62.clicked.connect(self.f_62_clicked)
        self.g_63.clicked.connect(self.g_63_clicked)
        self.h_64.clicked.connect(self.h_64_clicked)
        self.j_65.clicked.connect(self.j_65_clicked)
        self.k_66.clicked.connect(self.k_66_clicked)
        self.l_67.clicked.connect(self.l_67_clicked)
        self.semicolon_68.clicked.connect(self.semicolon_68_clicked)
        self.quote_69.clicked.connect(self.quote_69_clicked)
        self.enter_70.clicked.connect(self.enter_70_clicked)
        self.numfour_71.clicked.connect(self.numfour_71_clicked)
        self.numfive_72.clicked.connect(self.numfive_72_clicked)
        self.numsix_73.clicked.connect(self.numsix_73_clicked)
        self.lshift_74.clicked.connect(self.lshift_74_clicked)
        self.z_75.clicked.connect(self.z_75_clicked)
        self.x_76.clicked.connect(self.x_76_clicked)
        self.c_77.clicked.connect(self.c_77_clicked)
        self.v_78.clicked.connect(self.v_78_clicked)
        self.b_79.clicked.connect(self.b_79_clicked)
        self.n_80.clicked.connect(self.n_80_clicked)
        self.m_81.clicked.connect(self.m_81_clicked)
        self.comma_82.clicked.connect(self.comma_82_clicked)
        self.period_83.clicked.connect(self.period_83_clicked)
        self.forewardslash_84.clicked.connect(self.forewardslash_84_clicked)
        self.rshift_85.clicked.connect(self.rshift_85_clicked)
        self.up_86.clicked.connect(self.up_86_clicked)
        self.numone_87.clicked.connect(self.numone_87_clicked)
        self.numtwo_88.clicked.connect(self.numtwo_88_clicked)
        self.numthree_89.clicked.connect(self.numthree_89_clicked)
        self.numenter_90.clicked.connect(self.numenter_90_clicked)
        self.control_91.clicked.connect(self.control_91_clicked)
        self.super_92.clicked.connect(self.super_92_clicked)
        self.alt_93.clicked.connect(self.alt_93_clicked)
        self.space_94.clicked.connect(self.space_94_clicked)
        self.ralt_95.clicked.connect(self.ralt_95_clicked)
        self.fn_96.clicked.connect(self.fn_96_clicked)
        self.menu_97.clicked.connect(self.menu_97_clicked)
        self.rcontrol_98.clicked.connect(self.rcontrol_98_clicked)
        self.left_99.clicked.connect(self.left_99_clicked)
        self.own_100.clicked.connect(self.own_100_clicked)
        self.right_101.clicked.connect(self.right_101_clicked)
        self.numzero_102.clicked.connect(self.numzero_102_clicked)
        self.ecimalpoint_103.clicked.connect(self.ecimalpoint_103_clicked)
        self.setall.clicked.connect(self.setall_clicked)
        self.save.clicked.connect(self.save_clicked)
        self.load.clicked.connect(self.load_clicked)
        self.parse.clicked.connect(self.parse_clicked)
        self.runscript.clicked.connect(self.runscript_clicked)

    def escape_0_clicked(self):
        self.key_set_color(0)

    def f1_1_clicked(self):
        self.key_set_color(1)

    def f2_2_clicked(self):
        self.key_set_color(2)

    def f3_3_clicked(self):
        self.key_set_color(3)

    def f4_4_clicked(self):
        self.key_set_color(4)

    def f5_5_clicked(self):
        self.key_set_color(5)

    def f6_6_clicked(self):
        self.key_set_color(6)

    def f7_7_clicked(self):
        self.key_set_color(7)

    def f8_8_clicked(self):
        self.key_set_color(8)

    def f9_9_clicked(self):
        self.key_set_color(9)

    def f10_10_clicked(self):
        self.key_set_color(10)

    def f11_11_clicked(self):
        self.key_set_color(11)

    def f12_12_clicked(self):
        self.key_set_color(12)

    def prtsc_13_clicked(self):
        self.key_set_color(13)

    def scrolllock_14_clicked(self):
        self.key_set_color(14)

    def pause_15_clicked(self):
        self.key_set_color(15)

    def backtick_16_clicked(self):
        self.key_set_color(16)

    def onekey_17_clicked(self):
        self.key_set_color(17)

    def twokey_18_clicked(self):
        self.key_set_color(18)

    def threekey_19_clicked(self):
        self.key_set_color(19)

    def fourkey_20_clicked(self):
        self.key_set_color(20)

    def fivekey_21_clicked(self):
        self.key_set_color(21)

    def sixkey_22_clicked(self):
        self.key_set_color(22)

    def sevenkey_23_clicked(self):
        self.key_set_color(23)

    def eightkey_24_clicked(self):
        self.key_set_color(24)

    def ninekey_25_clicked(self):
        self.key_set_color(25)

    def zerokey_26_clicked(self):
        self.key_set_color(26)

    def minuskey_27_clicked(self):
        self.key_set_color(27)

    def equalskey_28_clicked(self):
        self.key_set_color(28)

    def backspace_29_clicked(self):
        self.key_set_color(29)

    def nsert_30_clicked(self):
        self.key_set_color(30)

    def home_31_clicked(self):
        self.key_set_color(31)

    def pageup_32_clicked(self):
        self.key_set_color(32)

    def numlock_33_clicked(self):
        self.key_set_color(33)

    def vide_34_clicked(self):
        self.key_set_color(34)

    def multiply_35_clicked(self):
        self.key_set_color(35)

    def subtract_36_clicked(self):
        self.key_set_color(36)

    def tab_37_clicked(self):
        self.key_set_color(37)

    def q_38_clicked(self):
        self.key_set_color(38)

    def w_39_clicked(self):
        self.key_set_color(39)

    def e_40_clicked(self):
        self.key_set_color(40)

    def r_41_clicked(self):
        self.key_set_color(41)

    def t_42_clicked(self):
        self.key_set_color(42)

    def y_43_clicked(self):
        self.key_set_color(43)

    def u_44_clicked(self):
        self.key_set_color(44)

    def _45_clicked(self):
        self.key_set_color(45)

    def o_46_clicked(self):
        self.key_set_color(46)

    def p_47_clicked(self):
        self.key_set_color(47)

    def lbracket_48_clicked(self):
        self.key_set_color(48)

    def rbracket_49_clicked(self):
        self.key_set_color(49)

    def backslash_50_clicked(self):
        self.key_set_color(50)

    def elete_51_clicked(self):
        self.key_set_color(51)

    def end_52_clicked(self):
        self.key_set_color(52)

    def pagedown_53_clicked(self):
        self.key_set_color(53)

    def numseven_54_clicked(self):
        self.key_set_color(54)

    def numeight_55_clicked(self):
        self.key_set_color(55)

    def numnine_56_clicked(self):
        self.key_set_color(56)

    def add_57_clicked(self):
        self.key_set_color(57)

    def capslock_58_clicked(self):
        self.key_set_color(58)

    def a_59_clicked(self):
        self.key_set_color(59)

    def s_60_clicked(self):
        self.key_set_color(60)

    def _61_clicked(self):
        self.key_set_color(61)

    def f_62_clicked(self):
        self.key_set_color(62)

    def g_63_clicked(self):
        self.key_set_color(63)

    def h_64_clicked(self):
        self.key_set_color(64)

    def j_65_clicked(self):
        self.key_set_color(65)

    def k_66_clicked(self):
        self.key_set_color(66)

    def l_67_clicked(self):
        self.key_set_color(67)

    def semicolon_68_clicked(self):
        self.key_set_color(68)

    def quote_69_clicked(self):
        self.key_set_color(69)

    def enter_70_clicked(self):
        self.key_set_color(70)

    def numfour_71_clicked(self):
        self.key_set_color(71)

    def numfive_72_clicked(self):
        self.key_set_color(72)

    def numsix_73_clicked(self):
        self.key_set_color(73)

    def lshift_74_clicked(self):
        self.key_set_color(74)

    def z_75_clicked(self):
        self.key_set_color(75)

    def x_76_clicked(self):
        self.key_set_color(76)

    def c_77_clicked(self):
        self.key_set_color(77)

    def v_78_clicked(self):
        self.key_set_color(78)

    def b_79_clicked(self):
        self.key_set_color(79)

    def n_80_clicked(self):
        self.key_set_color(80)

    def m_81_clicked(self):
        self.key_set_color(81)

    def comma_82_clicked(self):
        self.key_set_color(82)

    def period_83_clicked(self):
        self.key_set_color(83)

    def forewardslash_84_clicked(self):
        self.key_set_color(84)

    def rshift_85_clicked(self):
        self.key_set_color(85)

    def up_86_clicked(self):
        self.key_set_color(86)

    def numone_87_clicked(self):
        self.key_set_color(87)

    def numtwo_88_clicked(self):
        self.key_set_color(88)

    def numthree_89_clicked(self):
        self.key_set_color(89)

    def numenter_90_clicked(self):
        self.key_set_color(90)

    def control_91_clicked(self):
        self.key_set_color(91)

    def super_92_clicked(self):
        self.key_set_color(92)

    def alt_93_clicked(self):
        self.key_set_color(93)

    def space_94_clicked(self):
        self.key_set_color(94)

    def ralt_95_clicked(self):
        self.key_set_color(95)

    def fn_96_clicked(self):
        self.key_set_color(96)

    def menu_97_clicked(self):
        self.key_set_color(97)

    def rcontrol_98_clicked(self):
        self.key_set_color(98)

    def left_99_clicked(self):
        self.key_set_color(99)

    def own_100_clicked(self):
        self.key_set_color(100)

    def right_101_clicked(self):
        self.key_set_color(101)

    def numzero_102_clicked(self):
        self.key_set_color(102)

    def ecimalpoint_103_clicked(self):
        self.key_set_color(103)
       
    def update_working_colors(self):
        self.escape_0.setStyleSheet('QPushButton {background-color: '+colors_working[0]+'; color: black;}') #initialize colors
        self.f1_1.setStyleSheet('QPushButton {background-color: '+colors_working[1]+'; color: black;}') #initialize colors
        self.f2_2.setStyleSheet('QPushButton {background-color: '+colors_working[2]+'; color: black;}') #initialize colors
        self.f3_3.setStyleSheet('QPushButton {background-color: '+colors_working[3]+'; color: black;}') #initialize colors
        self.f4_4.setStyleSheet('QPushButton {background-color: '+colors_working[4]+'; color: black;}') #initialize colors
        self.f5_5.setStyleSheet('QPushButton {background-color: '+colors_working[5]+'; color: black;}') #initialize colors
        self.f6_6.setStyleSheet('QPushButton {background-color: '+colors_working[6]+'; color: black;}') #initialize colors
        self.f7_7.setStyleSheet('QPushButton {background-color: '+colors_working[7]+'; color: black;}') #initialize colors
        self.f8_8.setStyleSheet('QPushButton {background-color: '+colors_working[8]+'; color: black;}') #initialize colors
        self.f9_9.setStyleSheet('QPushButton {background-color: '+colors_working[9]+'; color: black;}') #initialize colors
        self.f10_10.setStyleSheet('QPushButton {background-color: '+colors_working[10]+'; color: black;}') #initialize colors
        self.f11_11.setStyleSheet('QPushButton {background-color: '+colors_working[11]+'; color: black;}') #initialize colors
        self.f12_12.setStyleSheet('QPushButton {background-color: '+colors_working[12]+'; color: black;}') #initialize colors
        self.prtsc_13.setStyleSheet('QPushButton {background-color: '+colors_working[13]+'; color: black;}') #initialize colors
        self.scrolllock_14.setStyleSheet('QPushButton {background-color: '+colors_working[14]+'; color: black;}') #initialize colors
        self.pause_15.setStyleSheet('QPushButton {background-color: '+colors_working[15]+'; color: black;}') #initialize colors
        self.backtick_16.setStyleSheet('QPushButton {background-color: '+colors_working[16]+'; color: black;}') #initialize colors
        self.onekey_17.setStyleSheet('QPushButton {background-color: '+colors_working[17]+'; color: black;}') #initialize colors
        self.twokey_18.setStyleSheet('QPushButton {background-color: '+colors_working[18]+'; color: black;}') #initialize colors
        self.threekey_19.setStyleSheet('QPushButton {background-color: '+colors_working[19]+'; color: black;}') #initialize colors
        self.fourkey_20.setStyleSheet('QPushButton {background-color: '+colors_working[20]+'; color: black;}') #initialize colors
        self.fivekey_21.setStyleSheet('QPushButton {background-color: '+colors_working[21]+'; color: black;}') #initialize colors
        self.sixkey_22.setStyleSheet('QPushButton {background-color: '+colors_working[22]+'; color: black;}') #initialize colors
        self.sevenkey_23.setStyleSheet('QPushButton {background-color: '+colors_working[23]+'; color: black;}') #initialize colors
        self.eightkey_24.setStyleSheet('QPushButton {background-color: '+colors_working[24]+'; color: black;}') #initialize colors
        self.ninekey_25.setStyleSheet('QPushButton {background-color: '+colors_working[25]+'; color: black;}') #initialize colors
        self.zerokey_26.setStyleSheet('QPushButton {background-color: '+colors_working[26]+'; color: black;}') #initialize colors
        self.minuskey_27.setStyleSheet('QPushButton {background-color: '+colors_working[27]+'; color: black;}') #initialize colors
        self.equalskey_28.setStyleSheet('QPushButton {background-color: '+colors_working[28]+'; color: black;}') #initialize colors
        self.backspace_29.setStyleSheet('QPushButton {background-color: '+colors_working[29]+'; color: black;}') #initialize colors
        self.nsert_30.setStyleSheet('QPushButton {background-color: '+colors_working[30]+'; color: black;}') #initialize colors
        self.home_31.setStyleSheet('QPushButton {background-color: '+colors_working[31]+'; color: black;}') #initialize colors
        self.pageup_32.setStyleSheet('QPushButton {background-color: '+colors_working[32]+'; color: black;}') #initialize colors
        self.numlock_33.setStyleSheet('QPushButton {background-color: '+colors_working[33]+'; color: black;}') #initialize colors
        self.vide_34.setStyleSheet('QPushButton {background-color: '+colors_working[34]+'; color: black;}') #initialize colors
        self.multiply_35.setStyleSheet('QPushButton {background-color: '+colors_working[35]+'; color: black;}') #initialize colors
        self.subtract_36.setStyleSheet('QPushButton {background-color: '+colors_working[36]+'; color: black;}') #initialize colors
        self.tab_37.setStyleSheet('QPushButton {background-color: '+colors_working[37]+'; color: black;}') #initialize colors
        self.q_38.setStyleSheet('QPushButton {background-color: '+colors_working[38]+'; color: black;}') #initialize colors
        self.w_39.setStyleSheet('QPushButton {background-color: '+colors_working[39]+'; color: black;}') #initialize colors
        self.e_40.setStyleSheet('QPushButton {background-color: '+colors_working[40]+'; color: black;}') #initialize colors
        self.r_41.setStyleSheet('QPushButton {background-color: '+colors_working[41]+'; color: black;}') #initialize colors
        self.t_42.setStyleSheet('QPushButton {background-color: '+colors_working[42]+'; color: black;}') #initialize colors
        self.y_43.setStyleSheet('QPushButton {background-color: '+colors_working[43]+'; color: black;}') #initialize colors
        self.u_44.setStyleSheet('QPushButton {background-color: '+colors_working[44]+'; color: black;}') #initialize colors
        self._45.setStyleSheet('QPushButton {background-color: '+colors_working[45]+'; color: black;}') #initialize colors
        self.o_46.setStyleSheet('QPushButton {background-color: '+colors_working[46]+'; color: black;}') #initialize colors
        self.p_47.setStyleSheet('QPushButton {background-color: '+colors_working[47]+'; color: black;}') #initialize colors
        self.lbracket_48.setStyleSheet('QPushButton {background-color: '+colors_working[48]+'; color: black;}') #initialize colors
        self.rbracket_49.setStyleSheet('QPushButton {background-color: '+colors_working[49]+'; color: black;}') #initialize colors
        self.backslash_50.setStyleSheet('QPushButton {background-color: '+colors_working[50]+'; color: black;}') #initialize colors
        self.elete_51.setStyleSheet('QPushButton {background-color: '+colors_working[51]+'; color: black;}') #initialize colors
        self.end_52.setStyleSheet('QPushButton {background-color: '+colors_working[52]+'; color: black;}') #initialize colors
        self.pagedown_53.setStyleSheet('QPushButton {background-color: '+colors_working[53]+'; color: black;}') #initialize colors
        self.numseven_54.setStyleSheet('QPushButton {background-color: '+colors_working[54]+'; color: black;}') #initialize colors
        self.numeight_55.setStyleSheet('QPushButton {background-color: '+colors_working[55]+'; color: black;}') #initialize colors
        self.numnine_56.setStyleSheet('QPushButton {background-color: '+colors_working[56]+'; color: black;}') #initialize colors
        self.add_57.setStyleSheet('QPushButton {background-color: '+colors_working[57]+'; color: black;}') #initialize colors
        self.capslock_58.setStyleSheet('QPushButton {background-color: '+colors_working[58]+'; color: black;}') #initialize colors
        self.a_59.setStyleSheet('QPushButton {background-color: '+colors_working[59]+'; color: black;}') #initialize colors
        self.s_60.setStyleSheet('QPushButton {background-color: '+colors_working[60]+'; color: black;}') #initialize colors
        self._61.setStyleSheet('QPushButton {background-color: '+colors_working[61]+'; color: black;}') #initialize colors
        self.f_62.setStyleSheet('QPushButton {background-color: '+colors_working[62]+'; color: black;}') #initialize colors
        self.g_63.setStyleSheet('QPushButton {background-color: '+colors_working[63]+'; color: black;}') #initialize colors
        self.h_64.setStyleSheet('QPushButton {background-color: '+colors_working[64]+'; color: black;}') #initialize colors
        self.j_65.setStyleSheet('QPushButton {background-color: '+colors_working[65]+'; color: black;}') #initialize colors
        self.k_66.setStyleSheet('QPushButton {background-color: '+colors_working[66]+'; color: black;}') #initialize colors
        self.l_67.setStyleSheet('QPushButton {background-color: '+colors_working[67]+'; color: black;}') #initialize colors
        self.semicolon_68.setStyleSheet('QPushButton {background-color: '+colors_working[68]+'; color: black;}') #initialize colors
        self.quote_69.setStyleSheet('QPushButton {background-color: '+colors_working[69]+'; color: black;}') #initialize colors
        self.enter_70.setStyleSheet('QPushButton {background-color: '+colors_working[70]+'; color: black;}') #initialize colors
        self.numfour_71.setStyleSheet('QPushButton {background-color: '+colors_working[71]+'; color: black;}') #initialize colors
        self.numfive_72.setStyleSheet('QPushButton {background-color: '+colors_working[72]+'; color: black;}') #initialize colors
        self.numsix_73.setStyleSheet('QPushButton {background-color: '+colors_working[73]+'; color: black;}') #initialize colors
        self.lshift_74.setStyleSheet('QPushButton {background-color: '+colors_working[74]+'; color: black;}') #initialize colors
        self.z_75.setStyleSheet('QPushButton {background-color: '+colors_working[75]+'; color: black;}') #initialize colors
        self.x_76.setStyleSheet('QPushButton {background-color: '+colors_working[76]+'; color: black;}') #initialize colors
        self.c_77.setStyleSheet('QPushButton {background-color: '+colors_working[77]+'; color: black;}') #initialize colors
        self.v_78.setStyleSheet('QPushButton {background-color: '+colors_working[78]+'; color: black;}') #initialize colors
        self.b_79.setStyleSheet('QPushButton {background-color: '+colors_working[79]+'; color: black;}') #initialize colors
        self.n_80.setStyleSheet('QPushButton {background-color: '+colors_working[80]+'; color: black;}') #initialize colors
        self.m_81.setStyleSheet('QPushButton {background-color: '+colors_working[81]+'; color: black;}') #initialize colors
        self.comma_82.setStyleSheet('QPushButton {background-color: '+colors_working[82]+'; color: black;}') #initialize colors
        self.period_83.setStyleSheet('QPushButton {background-color: '+colors_working[83]+'; color: black;}') #initialize colors
        self.forewardslash_84.setStyleSheet('QPushButton {background-color: '+colors_working[84]+'; color: black;}') #initialize colors
        self.rshift_85.setStyleSheet('QPushButton {background-color: '+colors_working[85]+'; color: black;}') #initialize colors
        self.up_86.setStyleSheet('QPushButton {background-color: '+colors_working[86]+'; color: black;}') #initialize colors
        self.numone_87.setStyleSheet('QPushButton {background-color: '+colors_working[87]+'; color: black;}') #initialize colors
        self.numtwo_88.setStyleSheet('QPushButton {background-color: '+colors_working[88]+'; color: black;}') #initialize colors
        self.numthree_89.setStyleSheet('QPushButton {background-color: '+colors_working[89]+'; color: black;}') #initialize colors
        self.numenter_90.setStyleSheet('QPushButton {background-color: '+colors_working[90]+'; color: black;}') #initialize colors
        self.control_91.setStyleSheet('QPushButton {background-color: '+colors_working[91]+'; color: black;}') #initialize colors
        self.super_92.setStyleSheet('QPushButton {background-color: '+colors_working[92]+'; color: black;}') #initialize colors
        self.alt_93.setStyleSheet('QPushButton {background-color: '+colors_working[93]+'; color: black;}') #initialize colors
        self.space_94.setStyleSheet('QPushButton {background-color: '+colors_working[94]+'; color: black;}') #initialize colors
        self.ralt_95.setStyleSheet('QPushButton {background-color: '+colors_working[95]+'; color: black;}') #initialize colors
        self.fn_96.setStyleSheet('QPushButton {background-color: '+colors_working[96]+'; color: black;}') #initialize colors
        self.menu_97.setStyleSheet('QPushButton {background-color: '+colors_working[97]+'; color: black;}') #initialize colors
        self.rcontrol_98.setStyleSheet('QPushButton {background-color: '+colors_working[98]+'; color: black;}') #initialize colors
        self.left_99.setStyleSheet('QPushButton {background-color: '+colors_working[99]+'; color: black;}') #initialize colors
        self.own_100.setStyleSheet('QPushButton {background-color: '+colors_working[100]+'; color: black;}') #initialize colors
        self.right_101.setStyleSheet('QPushButton {background-color: '+colors_working[101]+'; color: black;}') #initialize colors
        self.numzero_102.setStyleSheet('QPushButton {background-color: '+colors_working[102]+'; color: black;}') #initialize colors
        self.ecimalpoint_103.setStyleSheet('QPushButton {background-color: '+colors_working[103]+'; color: black;}') #initialize colors

app = QtWidgets.QApplication(sys.argv)
app.setStyleSheet('QMainWindow{background-color: #333333;border: 13px solid #222222;}QColorDialog{background-color: #333333;border: 13px solid #222222;}')
window = MainWindow()
window.show()
app.exec()
