name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        shell: bash
        run: |
          curl -sL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py \
            | python -
      - name: Update PATH
        shell: bash
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Configure poetry
        shell: bash
        run: poetry config virtualenvs.in-project true
      - name: Install dependencies
        shell: bash
        run: poetry install
      - name: Run Black
        shell: bash
        run: poetry run black --check .
      - name: Run Flake8
        shell: bash
        run: poetry run flake8 rgb_control/